// Generated by js_of_ocaml
//# buildInfo:effects=false, kind=exe, use-js-string=true, version=5.4.0+git-5.3.0-54-g8128607c0d-dirty
(function(a){typeof
globalThis!=="object"&&(this?b():(a.defineProperty(a.prototype,"_T_",{configurable:true,get:b}),_T_));function
b(){var
b=this||self;b.globalThis=b;delete
a.prototype._T_}}(Object));(function(d){"use strict";var
aG=0xdfff,ap="Division_by_zero",aq="fd ",ay="ENOTEMPTY",S="ENOTDIR",ax="Sys_blocked_io",ao=": file descriptor already closed",aF="^",W="rmdir",aw=": closedir failed",j=0x80,an=" : is a directory",P=" : flags Open_rdonly and Open_wronly are not compatible",aE="Not_found",f="",aD="EEXIST",R="EBADF",av=0xdc00,V="ENOENT",E=": No such file or directory",au="Pervasives.do_at_exit",L=" : file already exists",at=65536,c=248,u=0x3f,U=": Not a directory",w=1024,aK="/static/",aL="closedir",am="Sys_error",l="/",al=0x800,C='"',N="mkdir",O=128,ak="End_of_file",as="Invalid_argument",aB="Out_of_memory",aC=512,aJ=0xe0,ar="Match_failure",aI=0xf0,aj="Stack_overflow",aA="jsError",Q="fs",T="Failure",az="Assert_failure",ai="Undefined_recursive_module",M=" : flags Open_text and Open_binary are not compatible",D="Unix.Unix_error",aH="([^/]+)";function
a0(a){return a[1]}function
F(d,c){var
f=d.l>=0?d.l:d.l=d.length,e=c.length,b=f-e;if(b==0)return d.apply(null,c);else if(b<0){var
a=d.apply(null,c.slice(0,f));if(typeof
a!=="function")return a;return F(a,c.slice(f))}else{switch(b){case
1:{var
a=function(a){var
f=new
Array(e+1);for(var
b=0;b<e;b++)f[b]=c[b];f[e]=a;return d.apply(null,f)};break}case
2:{var
a=function(a,b){var
g=new
Array(e+2);for(var
f=0;f<e;f++)g[f]=c[f];g[e]=a;g[e+1]=b;return d.apply(null,g)};break}default:var
a=function(){var
e=arguments.length==0?1:arguments.length,b=new
Array(c.length+e);for(var
a=0;a<c.length;a++)b[a]=c[a];for(var
a=0;a<arguments.length;a++)b[c.length+a]=arguments[a];return F(d,b)}}a.l=b;return a}}function
bp(a){var
b=d.process;if(b&&b.env&&b.env[a]!=undefined)return b.env[a];if(d.jsoo_static_env&&d.jsoo_static_env[a])return d.jsoo_static_env[a]}var
ad=0;(function(){var
c=bp("OCAMLRUNPARAM");if(c!==undefined){var
b=c.split(",");for(var
a=0;a<b.length;a++)if(b[a]=="b"){ad=1;break}else if(b[a].startsWith("b="))ad=+b[a].slice(2);else
continue}}());var
h=[0];function
a6(a,b){if(!a.js_error||b||a[0]==c)a.js_error=new
d.Error("Js exception containing backtrace");return a}function
ab(a,b){return ad?a6(a,b):a}function
bg(a,b){throw ab([0,a,b])}function
r(a){return a}function
ac(a,b){bg(a,r(b))}function
$(a){if(!h.Failure)h.Failure=[c,r(T),-3];ac(h.Failure,a)}function
ae(a){if(a.length<24){for(var
b=0;b<a.length;b++)if(a.charCodeAt(b)>127)return false;return true}else
return!/[^\x00-\x7f]/.test(a)}function
aV(a){for(var
l=f,d=f,h,g,i,b,c=0,k=a.length;c<k;c++){g=a.charCodeAt(c);if(g<j){for(var
e=c+1;e<k&&(g=a.charCodeAt(e))<j;e++);if(e-c>aC){d.substr(0,1);l+=d;d=f;l+=a.slice(c,e)}else
d+=a.slice(c,e);if(e==k)break;c=e}b=1;if(++c<k&&((i=a.charCodeAt(c))&-64)==O){h=i+(g<<6);if(g<aJ){b=h-0x3080;if(b<j)b=1}else{b=2;if(++c<k&&((i=a.charCodeAt(c))&-64)==O){h=i+(h<<6);if(g<aI){b=h-0xe2080;if(b<al||b>=0xd7ff&&b<0xe000)b=2}else{b=3;if(++c<k&&((i=a.charCodeAt(c))&-64)==O&&g<0xf5){b=i-0x3c82080+(h<<6);if(b<0x10000||b>0x10ffff)b=3}}}}}if(b<4){c-=b;d+="\ufffd"}else if(b>0xffff)d+=String.fromCharCode(0xd7c0+(b>>10),av+(b&0x3FF));else
d+=String.fromCharCode(b);if(d.length>w){d.substr(0,1);l+=d;d=f}}return l+d}function
aa(a){if(ae(a))return a;return aV(a)}function
B(){return typeof
d.process!=="undefined"&&typeof
d.process.versions!=="undefined"&&typeof
d.process.versions.node!=="undefined"}function
bq(){function
a(a){if(a.charAt(0)===l)return[f,a.substring(1)];return}function
b(a){var
h=/^([a-zA-Z]:|[\\/]{2}[^\\/]+[\\/]+[^\\/]+)?([\\/])?([\s\S]*?)$/,b=h.exec(a),c=b[1]||f,e=Boolean(c&&c.charAt(1)!==":");if(Boolean(b[2]||e)){var
d=b[1]||f,g=b[2]||f;return[d,a.substring(d.length+g.length)]}return}return B()&&d.process&&d.process.platform?d.process.platform==="win32"?b:a:a}var
af=bq();function
aU(a){return a.slice(-1)!==l?a+l:a}if(B()&&d.process&&d.process.cwd)var
z=d.process.cwd().replace(/\\/g,l);else
var
z="/static";z=aU(z);function
ba(a){a=aa(a);if(!af(a))a=z+a;var
e=af(a),d=e[1].split(l),b=[];for(var
c=0;c<d.length;c++)switch(d[c]){case"..":if(b.length>1)b.pop();break;case".":break;case"":break;default:b.push(d[c]);break}b.unshift(e[0]);b.orig=a;return b}function
bn(a){for(var
g=f,c=g,b,i,d=0,h=a.length;d<h;d++){b=a.charCodeAt(d);if(b<j){for(var
e=d+1;e<h&&(b=a.charCodeAt(e))<j;e++);if(e-d>aC){c.substr(0,1);g+=c;c=f;g+=a.slice(d,e)}else
c+=a.slice(d,e);if(e==h)break;d=e}if(b<al){c+=String.fromCharCode(0xc0|b>>6);c+=String.fromCharCode(j|b&u)}else if(b<0xd800||b>=aG)c+=String.fromCharCode(aJ|b>>12,j|b>>6&u,j|b&u);else if(b>=0xdbff||d+1==h||(i=a.charCodeAt(d+1))<av||i>aG)c+="\xef\xbf\xbd";else{d++;b=(b<<10)+i-0x35fdc00;c+=String.fromCharCode(aI|b>>18,j|b>>12&u,j|b>>6&u,j|b&u)}if(c.length>w){c.substr(0,1);g+=c;c=f}}return g+c}function
A(a){return ae(a)?r(a):r(bn(a))}var
br=["E2BIG","EACCES","EAGAIN",R,"EBUSY","ECHILD","EDEADLK","EDOM",aD,"EFAULT","EFBIG","EINTR","EINVAL","EIO","EISDIR","EMFILE","EMLINK","ENAMETOOLONG","ENFILE","ENODEV",V,"ENOEXEC","ENOLCK","ENOMEM","ENOSPC","ENOSYS",S,ay,"ENOTTY","ENXIO","EPERM","EPIPE","ERANGE","EROFS","ESPIPE","ESRCH","EXDEV","EWOULDBLOCK","EINPROGRESS","EALREADY","ENOTSOCK","EDESTADDRREQ","EMSGSIZE","EPROTOTYPE","ENOPROTOOPT","EPROTONOSUPPORT","ESOCKTNOSUPPORT","EOPNOTSUPP","EPFNOSUPPORT","EAFNOSUPPORT","EADDRINUSE","EADDRNOTAVAIL","ENETDOWN","ENETUNREACH","ENETRESET","ECONNABORTED","ECONNRESET","ENOBUFS","EISCONN","ENOTCONN","ESHUTDOWN","ETOOMANYREFS","ETIMEDOUT","ECONNREFUSED","EHOSTDOWN","EHOSTUNREACH","ELOOP","EOVERFLOW"];function
o(a,b,c,d){var
e=br.indexOf(a);if(e<0){if(d==null)d=-9999;e=[0,d]}var
g=[e,A(b||f),A(c||f)];return g}var
aS={};function
q(a){return aS[a]}function
n(a,b){throw ab([0,a].concat(b))}function
bj(a,b){if(a==0)return f;if(b.repeat)return b.repeat(a);var
d=f,c=0;for(;;){if(a&1)d+=b;a>>=1;if(a==0)return d;b+=b;c++;if(c==9)b.slice(0,1)}}function
I(a,b,c){var
d=String.fromCharCode;if(b==0&&c<=4096&&c==a.length)return d.apply(null,a);var
e=f;for(;0<c;b+=w,c-=w)e+=d.apply(null,a.slice(b,b+Math.min(c,w)));return e}function
a4(a){if(a.t==2)a.c+=bj(a.l-a.c.length,"\0");else
a.c=I(a.c,0,a.c.length);a.t=0}function
m(a,b,c){this.t=a;this.c=b;this.l=c}m.prototype.toString=function(){switch(this.t){case
9:return this.c;default:a4(this);case
0:if(ae(this.c)){this.t=9;return this.c}this.t=8;case
8:return this.c}};m.prototype.toUtf16=function(){var
a=this.toString();if(this.t==9)return a;return aV(a)};m.prototype.slice=function(){var
a=this.t==4?this.c.slice():this.c;return new
m(this.t,a,this.l)};function
a9(a){return a
instanceof
m}function
a_(a){return typeof
a==="string"&&!/[^\x00-\xff]/.test(a)}function
X(a){if(!(a
instanceof
Uint8Array))a=new
Uint8Array(a);return new
m(4,a,a.length)}function
aN(a){return new
m(0,a,a.length)}function
G(a){return a}function
Y(a){return aN(G(a))}function
e(a){ac(h.Sys_error,a)}function
aT(a){e(a+E)}function
_(a){var
c=new
Uint8Array(a.l),e=a.c,d=e.length,b=0;for(;b<d;b++)c[b]=e.charCodeAt(b);for(d=a.l;b<d;b++)c[b]=0;a.c=c;a.t=4;return c}function
bm(a){if(a.t!=4)_(a);return a.c}function
aQ(a){ac(h.Invalid_argument,a)}function
t(a){if(a<0)aQ("Bytes.create");return new
m(a?2:9,f,a)}function
bb(a){return a.l}function
y(a,b,c,d,e){if(e==0)return 0;if(d==0&&(e>=c.l||c.t==2&&e>=c.c.length)){c.c=a.t==4?I(a.c,b,e):b==0&&a.c.length==e?a.c:a.c.substr(b,e);c.t=c.c.length==c.l?0:2}else if(c.t==2&&d==c.c.length){c.c+=a.t==4?I(a.c,b,e):b==0&&a.c.length==e?a.c:a.c.substr(b,e);c.t=c.c.length==c.l?0:2}else{if(c.t!=4)_(c);var
g=a.c,h=c.c;if(a.t==4)if(d<=b)for(var
f=0;f<e;f++)h[d+f]=g[b+f];else
for(var
f=e-1;f>=0;f--)h[d+f]=g[b+f];else{var
i=Math.min(e,g.length-b);for(var
f=0;f<i;f++)h[d+f]=g.charCodeAt(b+f);for(;f<e;f++)h[d+f]=0}}return 0}function
aM(){}function
g(a){this.data=a}g.prototype=new
aM();g.prototype.constructor=g;g.prototype.truncate=function(a){var
b=this.data;this.data=t(a|0);y(b,0,this.data,0,a)};g.prototype.length=function(){return bb(this.data)};g.prototype.write=function(a,b,c,d){var
e=this.length();if(a+d>=e){var
f=t(a+d),g=this.data;this.data=f;y(g,0,this.data,0,e)}y(X(b),c,this.data,a,d);return 0};g.prototype.read=function(a,b,c,d){var
e=this.length();if(a+d>=e)d=e-a;if(d){var
f=t(d|0);y(this.data,a,f,0,d);b.set(bm(f),c)}return d};function
s(a,b,c){this.file=b;this.name=a;this.flags=c}s.prototype.err_closed=function(){e(this.name+ao)};s.prototype.length=function(){if(this.file)return this.file.length();this.err_closed()};s.prototype.write=function(a,b,c,d){if(this.file)return this.file.write(a,b,c,d);this.err_closed()};s.prototype.read=function(a,b,c,d){if(this.file)return this.file.read(a,b,c,d);this.err_closed()};s.prototype.close=function(){this.file=undefined};function
a(a,b){this.content={};this.root=a;this.lookupFun=b}a.prototype.nm=function(a){return this.root+a};a.prototype.create_dir_if_needed=function(a){var
d=a.split(l),c=f;for(var
b=0;b<d.length-1;b++){c+=d[b]+l;if(this.content[c])continue;this.content[c]=Symbol("directory")}};a.prototype.slash=function(a){return/\/$/.test(a)?a:a+l};a.prototype.lookup=function(a){if(!this.content[a]&&this.lookupFun){var
b=this.lookupFun(r(this.root),r(a));if(b!==0){this.create_dir_if_needed(a);this.content[a]=new
g(Y(b[1]))}}};a.prototype.exists=function(a){if(a==f)return 1;var
b=this.slash(a);if(this.content[b])return 1;this.lookup(a);return this.content[a]?1:0};a.prototype.isFile=function(a){return this.exists(a)&&!this.is_dir(a)?1:0};a.prototype.mkdir=function(a,b,c){var
g=c&&q(D);if(this.exists(a))if(g)n(g,o(aD,N,this.nm(a)));else
e(a+": File exists");var
d=/^(.*)\/[^/]+/.exec(a);d=d&&d[1]||f;if(!this.exists(d))if(g)n(g,o(V,N,this.nm(d)));else
e(d+E);if(!this.is_dir(d))if(g)n(g,o(S,N,this.nm(d)));else
e(d+U);this.create_dir_if_needed(this.slash(a))};a.prototype.rmdir=function(a,b){var
c=b&&q(D),d=a==f?f:this.slash(a),h=new
RegExp(aF+d+aH);if(!this.exists(a))if(c)n(c,o(V,W,this.nm(a)));else
e(a+E);if(!this.is_dir(a))if(c)n(c,o(S,W,this.nm(a)));else
e(a+U);for(var
g
in
this.content)if(g.match(h))if(c)n(c,o(ay,W,this.nm(a)));else
e(this.nm(a)+": Directory not empty");delete
this.content[d]};a.prototype.readdir=function(a){var
h=a==f?f:this.slash(a);if(!this.exists(a))e(a+E);if(!this.is_dir(a))e(a+U);var
i=new
RegExp(aF+h+aH),d={},c=[];for(var
g
in
this.content){var
b=g.match(i);if(b&&!d[b[1]]){d[b[1]]=true;c.push(b[1])}}return c};a.prototype.opendir=function(a,b){var
c=b&&q(D),d=this.readdir(a),f=false,g=0;return{readSync:function(){if(f)if(c)n(c,o(R,aL,this.nm(a)));else
e(a+aw);if(g==d.length)return null;var
b=d[g];g++;return{name:b}},closeSync:function(){if(f)if(c)n(c,o(R,aL,this.nm(a)));else
e(a+aw);f=true;d=[]}}};a.prototype.is_dir=function(a){if(a==f)return true;var
b=this.slash(a);return this.content[b]?1:0};a.prototype.unlink=function(a){var
b=this.content[a]?true:false;delete
this.content[a];return b};a.prototype.open=function(a,b){var
c;if(b.rdonly&&b.wronly)e(this.nm(a)+P);if(b.text&&b.binary)e(this.nm(a)+M);this.lookup(a);if(this.content[a]){if(this.is_dir(a))e(this.nm(a)+an);if(b.create&&b.excl)e(this.nm(a)+L);c=this.content[a];if(b.truncate)c.truncate()}else if(b.create){this.create_dir_if_needed(a);this.content[a]=new
g(t(0));c=this.content[a]}else
aT(this.nm(a));return new
s(this.nm(a),c,b)};a.prototype.open=function(a,b){var
c;if(b.rdonly&&b.wronly)e(this.nm(a)+P);if(b.text&&b.binary)e(this.nm(a)+M);this.lookup(a);if(this.content[a]){if(this.is_dir(a))e(this.nm(a)+an);if(b.create&&b.excl)e(this.nm(a)+L);c=this.content[a];if(b.truncate)c.truncate()}else if(b.create){this.create_dir_if_needed(a);this.content[a]=new
g(t(0));c=this.content[a]}else
aT(this.nm(a));return new
s(this.nm(a),c,b)};a.prototype.register=function(a,b){var
c;if(this.content[a])e(this.nm(a)+L);if(a9(b))c=new
g(b);if(a_(b))c=new
g(Y(b));else if(b
instanceof
Array)c=new
g(X(b));else if(typeof
b==="string")c=new
g(aN(b));else if(b.toString){var
d=Y(A(b.toString()));c=new
g(d)}if(c){this.create_dir_if_needed(a);this.content[a]=c}else
e(this.nm(a)+" : registering file with invalid content type")};a.prototype.constructor=a;function
bf(a){return a.length}function
bk(a,b){return a.charCodeAt(b)}function
bu(a){var
d=bf(a),c=new
Array(d),b=0;for(;b<d;b++)c[b]=bk(a,b);return c}function
a2(){aQ("index out of bounds")}function
a3(a,b,c){c&=0xff;if(a.t!=4){if(b==a.c.length){a.c+=String.fromCharCode(c);if(b+1==a.l)a.t=0;return 0}_(a)}a.c[b]=c;return 0}function
bs(a,b,c){if(b>>>0>=a.l)a2();return a3(a,b,c)}function
k(a,b){this.fs=require(Q);this.fd=a;this.flags=b}k.prototype=new
aM();k.prototype.constructor=k;k.prototype.truncate=function(a){try{this.fs.ftruncateSync(this.fd,a|0)}catch(f){e(f.toString())}};k.prototype.length=function(){try{return this.fs.fstatSync(this.fd).size}catch(f){e(f.toString())}};k.prototype.write=function(a,b,c,d){try{if(this.flags.isCharacterDevice)this.fs.writeSync(this.fd,b,c,d);else
this.fs.writeSync(this.fd,b,c,d,a)}catch(f){e(f.toString())}return 0};k.prototype.read=function(a,b,c,d){try{if(this.flags.isCharacterDevice)var
f=this.fs.readSync(this.fd,b,c,d);else
var
f=this.fs.readSync(this.fd,b,c,d,a);return f}catch(f){e(f.toString())}};k.prototype.close=function(){try{this.fs.closeSync(this.fd);return 0}catch(f){e(f.toString())}};function
b(a){this.fs=require(Q);this.root=a}b.prototype.nm=function(a){return this.root+a};b.prototype.exists=function(a){try{return this.fs.existsSync(this.nm(a))?1:0}catch(f){return 0}};b.prototype.isFile=function(a){try{return this.fs.statSync(this.nm(a)).isFile()?1:0}catch(f){e(f.toString())}};b.prototype.mkdir=function(a,b,c){try{this.fs.mkdirSync(this.nm(a),{mode:b});return 0}catch(f){this.raise_nodejs_error(f,c)}};b.prototype.rmdir=function(a,b){try{this.fs.rmdirSync(this.nm(a));return 0}catch(f){this.raise_nodejs_error(f,b)}};b.prototype.readdir=function(a,b){try{return this.fs.readdirSync(this.nm(a))}catch(f){this.raise_nodejs_error(f,b)}};b.prototype.is_dir=function(a){try{return this.fs.statSync(this.nm(a)).isDirectory()?1:0}catch(f){e(f.toString())}};b.prototype.unlink=function(a,b){try{var
c=this.fs.existsSync(this.nm(a))?1:0;this.fs.unlinkSync(this.nm(a));return c}catch(f){this.raise_nodejs_error(f,b)}};b.prototype.open=function(a,b,c){var
d=require("constants"),e=0;for(var
h
in
b)switch(h){case"rdonly":e|=d.O_RDONLY;break;case"wronly":e|=d.O_WRONLY;break;case"append":e|=d.O_WRONLY|d.O_APPEND;break;case"create":e|=d.O_CREAT;break;case"truncate":e|=d.O_TRUNC;break;case"excl":e|=d.O_EXCL;break;case"binary":e|=d.O_BINARY;break;case"text":e|=d.O_TEXT;break;case"nonblock":e|=d.O_NONBLOCK;break}try{var
f=this.fs.openSync(this.nm(a),e),g=this.fs.lstatSync(this.nm(a)).isCharacterDevice();b.isCharacterDevice=g;return new
k(f,b)}catch(f){this.raise_nodejs_error(f,c)}};b.prototype.rename=function(a,b,c){try{this.fs.renameSync(this.nm(a),this.nm(b))}catch(f){this.raise_nodejs_error(f,c)}};b.prototype.stat=function(a,b){try{var
c=this.fs.statSync(this.nm(a));return this.stats_from_js(c)}catch(f){this.raise_nodejs_error(f,b)}};b.prototype.lstat=function(a,b){try{var
c=this.fs.lstatSync(this.nm(a));return this.stats_from_js(c)}catch(f){this.raise_nodejs_error(f,b)}};b.prototype.symlink=function(a,b,c,d){try{this.fs.symlinkSync(this.nm(b),this.nm(c),a?"dir":"file");return 0}catch(f){this.raise_nodejs_error(f,d)}};b.prototype.readlink=function(a,b){try{var
c=this.fs.readlinkSync(this.nm(a),"utf8");return A(c)}catch(f){this.raise_nodejs_error(f,b)}};b.prototype.opendir=function(a,b){try{return this.fs.opendirSync(this.nm(a))}catch(f){this.raise_nodejs_error(f,b)}};b.prototype.raise_nodejs_error=function(a,b){var
c=q(D);if(b&&c){var
d=o(a.code,a.syscall,a.path,a.errno);n(c,d)}else
e(a.toString())};b.prototype.stats_from_js=function(a){var
b;if(a.isFile())b=0;else if(a.isDirectory())b=1;else if(a.isCharacterDevice())b=2;else if(a.isBlockDevice())b=3;else if(a.isSymbolicLink())b=4;else if(a.isFIFO())b=5;else if(a.isSocket())b=6;return[0,a.dev,a.ino,b,a.mode,a.nlink,a.uid,a.gid,a.rdev,a.size,a.atimeMs,a.mtimeMs,a.ctimeMs]};b.prototype.constructor=b;function
aP(a){var
b=af(a);if(!b)return;return b[0]+l}var
H=aP(z)||$("unable to compute caml_root"),v=[];if(B())v.push({path:H,device:new
b(H)});else
v.push({path:H,device:new
a(H)});v.push({path:aK,device:new
a(aK)});function
aX(a){var
i=ba(a),a=i.join(l),h=aU(a),d;for(var
g=0;g<v.length;g++){var
c=v[g];if(h.search(c.path)==0&&(!d||d.path.length<c.path.length))d={path:c.path,device:c.device,rest:a.substring(c.path.length,a.length)}}if(!d&&B()){var
f=aP(a);if(f&&f.match(/^[a-zA-Z]:\/$/)){var
c={path:f,device:new
b(f)};v.push(c);d={path:c.path,device:c.device,rest:a.substring(c.path.length,a.length)}}}if(d)return d;e("no device found for "+h)}function
a5(a,b){var
c=aX(a);if(!c.device.register)$("cannot register file");c.device.register(c.rest,b);return 0}function
aW(a,b){var
a=r(a),b=r(b);return a5(a,b)}function
a8(){var
b=d.caml_fs_tmp;if(b)for(var
a=0;a<b.length;a++)aW(b[a].name,b[a].content);d.jsoo_create_file=aW;d.caml_fs_tmp=[];return 0}var
p=new
Array();function
bc(a){var
b=p[a];if(!b.opened)e("Cannot flush a closed channel");if(!b.buffer||b.buffer_curr==0)return 0;if(b.output)b.output(I(b.buffer,0,b.buffer_curr));else
b.file.write(b.offset,b.buffer,0,b.buffer_curr);b.offset+=b.buffer_curr;b.buffer_curr=0;return 0}function
bl(a,b){if(b.name)try{var
d=require(Q),c=d.openSync(b.name,"rs");return new
k(c,b)}catch(f){}return new
k(a,b)}var
J=new
Array(3);function
x(a,b){g.call(this,t(0));this.log=function(a){return 0};if(a==1&&typeof
console.log=="function")this.log=console.log;else if(a==2&&typeof
console.error=="function")this.log=console.error;else if(typeof
console.log=="function")this.log=console.log;this.flags=b}x.prototype.length=function(){return 0};x.prototype.write=function(a,b,c,d){if(this.log){if(d>0&&c>=0&&c+d<=b.length&&b[c+d-1]==10)d--;var
f=t(d);y(X(b),c,f,0,d);this.log(f.toUtf16());return 0}e(this.fd+ao)};x.prototype.read=function(a,b,c,d){e(this.fd+": file descriptor is write only")};x.prototype.close=function(){this.log=undefined};function
K(a,b){if(b==undefined)b=J.length;J[b]=a;return b|0}function
bt(a,b,c){var
d={};while(b){switch(b[1]){case
0:d.rdonly=1;break;case
1:d.wronly=1;break;case
2:d.append=1;break;case
3:d.create=1;break;case
4:d.truncate=1;break;case
5:d.excl=1;break;case
6:d.binary=1;break;case
7:d.text=1;break;case
8:d.nonblock=1;break}b=b[2]}if(d.rdonly&&d.wronly)e(G(a)+P);if(d.text&&d.binary)e(G(a)+M);var
f=aX(a),g=f.device.open(f.rest,d);return K(g,undefined)}(function(){function
a(a,b){return B()?bl(a,b):new
x(a,b)}K(a(0,{rdonly:1,altname:"/dev/stdin",isCharacterDevice:true}),0);K(a(1,{buffered:2,wronly:1,isCharacterDevice:true}),1);K(a(2,{buffered:2,wronly:1,isCharacterDevice:true}),2)}());function
bd(a){var
b=J[a];if(b.flags.wronly)e(aq+a+" is writeonly");var
d=null,c={file:b,offset:b.flags.append?b.length():0,fd:a,opened:true,out:false,buffer_curr:0,buffer_max:0,buffer:new
Uint8Array(at),refill:d};p[c.fd]=c;return c.fd}function
aR(a){var
b=J[a];if(b.flags.rdonly)e(aq+a+" is readonly");var
d=b.flags.buffered!==undefined?b.flags.buffered:1,c={file:b,offset:b.flags.append?b.length():0,fd:a,opened:true,out:true,buffer_curr:0,buffer:new
Uint8Array(at),buffered:d};p[c.fd]=c;return c.fd}function
be(){var
b=0;for(var
a=0;a<p.length;a++)if(p[a]&&p[a].opened&&p[a].out)b=[0,p[a].fd,b];return b}var
Z=F;function
a1(a){var
b;while(a)if(aa(a[1][1])=="SYJS"){b=a[1][2];break}else
a=a[2];var
d={};if(b)for(var
c=1;c<b.length;c++)d[aa(b[c][1])]=b[c][2];return d}function
i(a,b,c){if(c){var
e=c;if(d.toplevelReloc)a=Z(d.toplevelReloc,[e]);else if(h.toc){if(!h.symbols)h.symbols=a1(h.toc);var
f=h.symbols[e];if(f>=0)a=f;else
$("caml_register_global: cannot locate "+e)}}h[a+1]=b;if(c)h[c]=b}function
bh(a,b){aS[G(a)]=b;return 0}function
bo(a){{if(a
instanceof
Array)return a;var
b;if(d.RangeError&&a
instanceof
d.RangeError&&a.message&&a.message.match(/maximum call stack/i))b=h.Stack_overflow;else if(d.InternalError&&a
instanceof
d.InternalError&&a.message&&a.message.match(/too much recursion/i))b=h.Stack_overflow;else if(a
instanceof
d.Error&&q(aA))b=[0,q(aA),a];else
b=[0,h.Failure,A(String(a))];if(a
instanceof
d.Error)b.js_error=a;return b}}function
a$(a){switch(a[2]){case-8:case-11:case-12:return 1;default:return 0}}function
a7(a){var
b=f;if(a[0]==0){b+=a[1][1];if(a.length==3&&a[2][0]==0&&a$(a[1]))var
g=a[2],h=1;else
var
h=2,g=a;b+="(";for(var
e=h;e<g.length;e++){if(e>h)b+=", ";var
d=g[e];if(typeof
d=="number")b+=d.toString();else if(d
instanceof
m)b+=C+d.toString()+C;else if(typeof
d=="string")b+=C+d.toString()+C;else
b+="_"}b+=")"}else if(a[0]==c)b+=a[1];return b}function
aO(a){if(a
instanceof
Array&&(a[0]==0||a[0]==c)){var
d=q("Printexc.handle_uncaught_exception");if(d)Z(d,[a,false]);else{var
e=a7(a),b=q(au);if(b)Z(b,[0]);console.error("Fatal error: exception "+e+"\n");if(a.js_error)throw a.js_error}}else
throw a}function
bi(){var
c=d.process;if(c&&c.on)c.on("uncaughtException",function(a,b){aO(a);c.exit(2)});else if(d.addEventListener)d.addEventListener("error",function(a){if(a.error)aO(a.error)})}bi();function
aZ(a,b){return(a.l>=0?a.l:a.l=a.length)==1?a(b):F(a,[b])}a8();var
ag=[c,am,-2];i(11,[c,ai,-12],ai);i(10,[c,az,-11],az);i(9,[c,ax,-10],ax);i(8,[c,aj,-9],aj);i(7,[c,ar,-8],ar);i(6,[c,aE,-7],aE);i(5,[c,ap,-6],ap);i(4,[c,ak,-5],ak);i(3,[c,as,-4],as);i(2,[c,T,-3],T);i(1,ag,am);i(0,[c,aB,-1],aB);bd(0);aR(1);aR(2);var
aY=[0,function(a){var
b=be(0);for(;;){if(!b)return 0;var
d=b[2],e=b[1];try{bc(e)}catch(f){var
c=bo(f);if(c[1]!==ag)throw ab(c,0)}var
b=d}}];function
ah(a){return aZ(a0(aY),0)}bh(au,ah);ah(0);return}(globalThis));
